baseURL = "http://richard-juday.net/"
canonifyurls = true
categoryPagination = 10
defaultContentLanguage = "en-us"
languageCode = "en-us"
paginate = 7
theme = "hugo-tranquilpeak-theme"
title = "Richard Juday"
[author]
bio = ""
job = "Engineer"
location = "Longmont, Colorado, USA"
name = "Richard Juday"
picture = "images/profile_photo.jpg"
[[menu.links]]
identifier = "publications"
name = "Publications"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-book\"></i>"
url = "/patents-and-publications"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
url = "/#about"
weight = 5
[[menu.main]]
identifier = "archives"
name = "Archives"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
url = "/archives"
weight = 4
[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/tags"
weight = 3
[[menu.main]]
identifier = "categories"
name = "Categories"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
url = "/categories"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"
weight = 1
[[menu.misc]]
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
url = "/index.xml"
weight = 1
[params]
autothumbnailimage = true
clearreading = true
coverimage = "cover.jpg"
customcss = ["css/custom.css"]
description = "Richard Juday blog and CV"
hierarchicalcategories = true
imagegallery = true
keywords = ["optics", "physics"]
sidebarbehavior = 1
thumbnailimage = true
thumbnailimageposition = "bottom"
[params.footer]
copyright = "Richard Juday"
[params.header.rightlink]
class = ""
icon = ""
url = "/#about"
[params.sidebar.profile]
url = "/"
[permalinks]
post = "/:year/:month/:slug/"
[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
