[build]
    publish = "public"
    command = "hugo"

[context.production]
    [context.production.environment]
        HUGO_VERSION = "0.24"

[context.deploy-preview]
    command = "npm run build-preview"
    [context.deploy-preview.environment]
        HUGO_VERSION = "0.24"
